name: CI for libft

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (without "v" prefix, ex. 1.0.0)'
        default: '1.0.0'
      draft:
        description: 'Should new release be a draft?'
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: cd libft && make && make clean

      # - name: set tag
      #   id: newtag
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # tag=$(gh release view --json tagName --jq '.tagName')
      #     tag=$(git tag --list --sort='-version:refname' 'v*' | head -n1)
      #     echo "newtag=$tag" >> "$GITHUB_OUTPUT"

      - name: create artifact
        run: |
          mkdir release
          cp libft/libft.a release/libft.a

      - name: publish artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'release/libft.a'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: ${{ inputs.tag }}
          generateReleaseNotes: true
          draft: '${{ inputs.draft }}'
          name: "Some unique name: release/libft.a ${{ inputs.tag }}"

          # tag: ${{ steps.newtag.outputs.newtag }}
          # bodyFile: "body.md"
