name: CI for libft

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: echo maybe well install stuff here later

      - name: build
        run: cd libft && make && make clean

      - name: set tag
        id: newtag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # tag=$(gh release view --json tagName --jq '.tagName')
          tag=$(git tag --list --sort='-version:refname' 'v*' | head -n1)
          echo "newtag=$tag" >> "$GITHUB_OUTPUT"

      - name: create artifact
        run: |
          mkdir release
          cp libft/libft.a release/libft.a

      - name: publish artifact
        uses: ncipollo/release-action@v1
        with:
          name: "release/libft.a"
          tag: ${{ steps.newtag.outputs.newtag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "body.md"
