name: CI for libft

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: echo maybe well install stuff here later

      - name: build
        run: cd libft && make

      - name: create artifact
        run: |
          mkdir release
          cp libft/libft.a release/libft.a

      - name: publish artifact
        uses: ncipollo/release-action@v1
        with:
          name: "release/libft.a"
          bodyFile: "body.md"
